os: osx
language: node_js
node_js:
  - 10
cache: yarn
notifications:
  slack: v2land:xoeT2IXt8yCaUfMxoBbXrSZD
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
script:
  - cd ios && pod install && cd ..
  - yarn test
